dlrobertson/capsicum-rs

- src/fcntl.rs
- src/ioctl.rs
- src/lib.rs
- src/process.rs
- src/right.rs
- src/util.rs
- tests/lib.rs
- clippy cleanup
- `enter` and `get_mode` now return a `io::Result`
- Fix a stack overflow in IoctlRights::from_file
- Fix FFI bindings
- Add a test for unlimited ioctl rights
- Fix doc tests
- Fix definitions of fork() and wait()
> Multiple fixes and cleanup

- Cargo.toml
- tests/lib.rs
* Use the tempfile crate instead of hard-coding temporary file names
* Must use _exit(0) at the end of child processes, so we don't run the Rust destructors in both children and parents.
* Minimize use of `unsafe`
* Always run `cap_enter` in a child process.
> Improvements to the integration tests:

- Cargo.toml
- build.rs
- tests/lib.rs
* Must check the child process's exit status
* Must switch the panic handler to SIGABRT, since stack unwinding isn't safe after fork() (requires nightly).
> In the tests, correctly check if a child process paniced

- src/fcntl.rs
- src/ioctl.rs
- src/process.rs
- src/right.rs
Where possible, use libc's FFI definitions instead of our own.
Partially addresses #18
> Prefer to define FFI functions in libc

- Cargo.toml
- build.rs
- rustfmt.toml
- src/common.rs
- src/fcntl.rs
- src/ioctl.rs
- src/lib.rs
- src/right.rs
- src/util.rs
- tests/lib.rs
And use grouped use statements, enabled by edition 2018.
> Convert crate to 2021 edition

- Cargo.toml
- src/fcntl.rs
- src/ioctl.rs
- src/process.rs
- src/right.rs
> Move the remaining FFI definitions into libc

- src/common.rs
- src/fcntl.rs
- src/ioctl.rs
- src/lib.rs
- src/right.rs
- src/util.rs
- tests/lib.rs
CapErr simply served to wrap an io::Error around an enum that mainly just served to tell the user what function he had just called.  But the user already knew that.  Simpler just to return io::Error directly.  The only complication was Directory::open_file, which needs to handle a NulError.  I mapped that to io::Error with an ErrorKind of Other.
Fixes #25
> Replace CapErr with io::Error

- src/lib.rs
They were actually attached to the non-public "common" module.
> Fix the module-level docs

- capsicum/Cargo.toml
- Add a version for the casper-sys dependency. This is needed to publish to crates.io.
See [Specifying Path Dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies) for details.
- Add an `example.path` for the `guid` example.
> Fix capsicum manifest for cargo publish

- CHANGELOG.md
- capsicum/Cargo.toml
- capsicum/build.rs
- casper-sys/Cargo.toml
There were two problems:
* capsicum's build script deliberately aborted when building _on_ non-FreeBSD, instead of building _for_ non-FreeBSD.
* docs.rs always builds docs on Linux.  So crates that require bindgen at build time, like libnv-sys, generally fail to compile there. libnv-sys tries to detect if it's being built on docs.rs and stubs out the FFI functions instead.  However, it wasn't stubbing out enough functions for capsicum to build.  That's fixed in https://github.com/Inner-Heaven/libnv-rs/pull/28 .
Fixes #41
> Fix cross-compiling the docs

- .cirrus.yml
* Update FreeBSD 13 to 13.2.  13.1 will soon be EoL
* Use the lastest 14 snapshot instead of an old pinned version.
> Update CI images

- CHANGELOG.md
- capsicum/Cargo.toml
- capsicum/examples/getuid.rs
- capsicum/src/casper/mod.rs
This is more flexible than using const_cstr::ConstCStr.  It also fixes a RUSTSEC issue.  But it is unfortunately backwards-incompatible.
https://rustsec.org/advisories/RUSTSEC-2023-0020
> Use &'static CStr for capsicum::casper::Service::SERVICE_NAME

- Cargo.toml
It's the default for edition 2021, but not the default for workspaces.
> Switch to resolver=2 for the workspace

- .cirrus.yml
Because the google cloud image for that release is broken. https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272354
> Temporarily disable CI on FreeBSD 14

- CHANGELOG.md
- capsicum/src/process.rs
Because cap_getmode is defined as returning either "zero" or "non-zero"
Fixes #45
> capsicum::get_mode should return a bool

- .cirrus.yml
- capsicum/Cargo.toml
- capsicum/examples/getuid.rs
- capsicum/src/casper/mod.rs
If supplied with str, libnv will convert it to cstr.  Using cstr directly is more efficient.
Fixes #36
> Pass CStr to libnv instead of str

- .cirrus.yml
Because the FreeBSD 14 google cloud images are fixed.
> Revert "Temporarily disable CI on FreeBSD 14"

- capsicum/Cargo.toml
This was the last dependency still transitively pulling in syn-1.0
> Update the ctor dependency

- capsicum/Cargo.toml
The currently availble docs don't include the casper feature.
> Enable all features when building docs for docs.rs

- .cirrus.yml
Because it will be EoL at the end of the month.
> Stop testing on FreeBSD 12

- capsicum/examples/getuid.rs
- capsicum/src/casper/mod.rs
This allows the macros to work in consumer crates that "#[deny(missing_docs)]"
> In the Casper macros, fully document all public symbols

- .cirrus.yml
cargo-audit 0.18.3 does not work in Cirrus's environment
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=276557 https://github.com/rustsec/rustsec/issues/1058
> Fix cargo audit in CI

- capsicum/CHANGELOG.md
- capsicum/Cargo.toml
- capsicum/src/lib.rs
- capsicum/src/util.rs
- capsicum/tests/lib.rs
It was a wrapper around openat.  But cap-std contains a much more complete set of wrappers around the various *at methods.  Let's use it instead of reinventing the wheel.
Fixes #62
> Deprecate util::Directory

- capsicum/CHANGELOG.md
- capsicum/src/fcntl.rs
- capsicum/src/ioctl.rs
- capsicum/src/lib.rs
- capsicum/src/right.rs
- capsicum/src/util.rs
- capsicum/tests/lib.rs
* They are both now `Clone`.
* Their `new` methods no longer take arguments.  The value formerly supplied
as an argument must now be supplied by the `add` methods.
* `IoctlsBuilder`'s methods now pass by move.
* The `IoctlsBuilder::raw`, `FcntlsBuilder::raw`, `IoctlRights::new`, and
`FcntlRights::new` methods are all deprecated.
Fixes #46
> Overhaul the IoctlsBuilder and FcntlsBuilder APIs

- .cirrus.yml
- capsicum/CHANGELOG.md
- capsicum/src/lib.rs
- capsicum/src/right.rs
Also, deprecate FileRights::is_valid, which should no longer be necessary after #80.
> Document all public members

- capsicum/examples/getuid.rs
- capsicum/src/casper/mod.rs
Because internally, within the C library, they use nvlist_xfer.  That sends an nvlist to the Casper daemon and retrives one in return.  So they must use synchronization when called from multiple threads, so that threads' responses don't get interleaved.
No CHANGELOG entry necessary because prior to PR #66 it was impossible to use these functions from multiple threads anyway.
See https://reviews.freebsd.org/D42928
> Casper::{service_open, try_clone} must take &mut self

- casper-sys/Cargo.toml
To prevent two crates from linking to the same C library, which can cause havoc.  Also, add a Cargo category.
Reported by:	lib.rs maintainer dashboard
> Add the "links" property to casper-sys's Cargo.toml

- capsicum/Cargo.toml
- capsicum/examples/getuid.rs
- capsicum/src/casper/mod.rs
This is a new feature in Rust 1.77.0, which is already our MSRV.
> Use native cstr literals instead of the cstr crate

- capsicum/CHANGELOG.md
- capsicum/src/right.rs
This change was made for FreeBSD 11.0.  See
https://github.com/freebsd/freebsd-src/commit/bc1ace0b96e17338dccec5cb08e2a3a96ebfba3c
> Split Right::Linkat into LinkatSource and LinkatTarget

- capsicum/CHANGELOG.md
- capsicum/src/fcntl.rs
- capsicum/src/lib.rs
- capsicum/src/right.rs
- capsicum/src/util.rs
- capsicum/tests/lib.rs
They never offered any real advantage over using FcntlsRights and FileRights directly, other than providing symmetry with IoctlsBuilder.
> Deprecate FcntlsBuilder and RightsBuilder

- capsicum/CHANGELOG.md
I originally thought that it wouldn't cause any backwards-compatibility trouble, but it actually can.  It can require users to add a `mut` where previously there was none.
[skip ci]
> Add a changelog entry for PR #82

- capsicum/CHANGELOG.md
- capsicum/Cargo.toml
- capsicum/src/common.rs
- capsicum/src/fcntl.rs
- capsicum/src/ioctl.rs
- capsicum/src/right.rs
- capsicum/src/util.rs
Functions that previously took an AsRawFd argument now take an AsFd.
There's no real improvement in I/O Safety since no capsicum function
ever stored a RawFd anywhere.  This is mostly just for style.
Fixes #31
> Use I/O Safety

- .cirrus.yml
- capsicum/CHANGELOG.md
- capsicum/src/lib.rs
They were broken on docs.rs due to using the unstable doc_cfg feature. I do not know why docs.rs successfully built version 0.3.0.
Also, add a CI task to ensure that the docs continue to cross-compile successfully.
> Fix building the docs

- capsicum/CHANGELOG.md
- capsicum/Cargo.toml
Those were accidental and never intended to be exposed.  They are merely implementation details of the `casper` feature.
> Remove the `libnv` and `libnv-sys` features

- capsicum/CHANGELOG.md
- capsicum/Cargo.toml
- capsicum/src/right.rs
They aren't stable across different OS versions, and they probably never had any legitimate use in our consumers anyway.
> Deprecated the `Right::CAP_ALL*` and `Right::CAP_UNUSED*` constants

- .cirrus.yml
- capsicum/CHANGELOG.md
- capsicum/Cargo.toml
- capsicum/src/lib.rs
- capsicum/src/util.rs
* Suppress the unhelpful doc_overindented_list_items lint
* Fix io_other_error by using std::io::Error::Other, introduced in Rust 1.74.0 .
> Clippy cleanup
